# Changes here will be overwritten by Copier
_commit: 2024.08.29
_src_path: gh:zenml-io/template-e2e-batch
data_quality_checks: true
hyperparameters_tuning: true
metric_compare_promotion: true
notify_on_failures: true
notify_on_successes: false
open_source_license: none
product_name: e2e_ts_forecast
project_name: e2e_ts
target_environment: staging
version: 0.0.1
zenml_server_url: ''
